
-- Galleries
INSERT INTO galleries (id, title) VALUES (1, 'The Gong is Born');
INSERT INTO galleries (id, title) VALUES (2, 'SpringsGiving Dinner');
INSERT INTO galleries (id, title) VALUES (3, 'Project at the Gate 1');
INSERT INTO galleries (id, title) VALUES (4, 'Project at the Gate 2l');
INSERT INTO galleries (id, title) VALUES (5, 'Project at the Gate 3');
INSERT INTO galleries (id, title) VALUES (6, 'Project at the Gate 4');
INSERT INTO galleries (id, title) VALUES (7, 'Project at the Gate 5');
INSERT INTO galleries (id, title) VALUES (8, 'POW House');
INSERT INTO galleries (id, title) VALUES (9, 'modernsmoker, batch 1');
INSERT INTO galleries (id, title) VALUES (10, 'modernsmoker, batch 2');
INSERT INTO galleries (id, title) VALUES (11, 'modernsmoker, batch 3');
INSERT INTO galleries (id, title) VALUES (12, 'modernsmoker, batch 4');
INSERT INTO galleries (id, title) VALUES (13, 'Ultra Heatsink');
INSERT INTO galleries (id, title) VALUES (14, 'Epic Farwell to 2004');
INSERT INTO galleries (id, title) VALUES (15, 'Semiformal Dance');
INSERT INTO galleries (id, title) VALUES (16, 'Title');
INSERT INTO galleries (id, title) VALUES (17, 'Dance Party');
INSERT INTO galleries (id, title) VALUES (18, 'Dance Party');
INSERT INTO galleries (id, title) VALUES (19, '2008 Group Picture');
INSERT INTO galleries (id, title) VALUES (20, 'The Hit');
INSERT INTO galleries (id, title) VALUES (21, 'Spring Barbeque');
INSERT INTO galleries (id, title) VALUES (22, 'A typical evening around Tech House');
INSERT INTO galleries (id, title) VALUES (23, 'JavaSpook 2009');
INSERT INTO galleries (id, title) VALUES (24, 'Blueprints');
INSERT INTO galleries (id, title) VALUES (25, 'End of the Year Dinner');
INSERT INTO galleries (id, title) VALUES (26, 'Lasertag Guns');
INSERT INTO galleries (id, title) VALUES (27, 'Fall Barbeque');
INSERT INTO galleries (id, title) VALUES (28, 'Drop Night');
INSERT INTO galleries (id, title) VALUES (29, 'Javaspook');
INSERT INTO galleries (id, title) VALUES (30, 'Pre-1998 Photos');
INSERT INTO galleries (id, title) VALUES (31, 'Fall Semester 1998');
INSERT INTO galleries (id, title) VALUES (32, 'December 1998 Events');
INSERT INTO galleries (id, title) VALUES (33, 'Recruiting Events, 1999');
INSERT INTO galleries (id, title) VALUES (34, 'Spring Semester 1999');
INSERT INTO galleries (id, title) VALUES (35, 'The Tunnel of Doom (April 1999)');
INSERT INTO galleries (id, title) VALUES (36, 'The 1999 Spring Semi-Formal');
INSERT INTO galleries (id, title) VALUES (37, 'Orientation Week 1999');
INSERT INTO galleries (id, title) VALUES (38, 'Ratty Chess! (September 1999)');
INSERT INTO galleries (id, title) VALUES (39, 'Miscellaneous pictures (September 1999)');
INSERT INTO galleries (id, title) VALUES (40, 'Halloween 1999');
INSERT INTO galleries (id, title) VALUES (41, 'JavaSpook 1999');
INSERT INTO galleries (id, title) VALUES (42, 'The Ropes Course (November 1999)');
INSERT INTO galleries (id, title) VALUES (43, 'John''s Birthday (November 16, 1999)');
INSERT INTO galleries (id, title) VALUES (44, 'A Fall Barbecue (November 21, 1999)');
INSERT INTO galleries (id, title) VALUES (45, 'Birthday Party for Chris, Chris, Mike, and Ryan (November 22, 1999)');
INSERT INTO galleries (id, title) VALUES (46, 'Steve Wozniak Visits Tech House!!! (December 9, 1999)');
INSERT INTO galleries (id, title) VALUES (47, 'The End-of-Year Dinner (December 11, 1999)');
INSERT INTO galleries (id, title) VALUES (48, 'Spring Semester 2000');
INSERT INTO galleries (id, title) VALUES (49, 'Picklemania! (February 4, 2000)');
INSERT INTO galleries (id, title) VALUES (50, 'Techtime');
INSERT INTO galleries (id, title) VALUES (51, 'Drop Night (February 10, 2000)');
INSERT INTO galleries (id, title) VALUES (52, 'La Bastille!');
INSERT INTO galleries (id, title) VALUES (53, 'Commencement 2000');
INSERT INTO galleries (id, title) VALUES (54, 'End Of Year Dinner (Spring 2000)');
INSERT INTO galleries (id, title) VALUES (55, 'JavaSpook VI');
INSERT INTO galleries (id, title) VALUES (56, 'Spring 2001 by CChin');
INSERT INTO galleries (id, title) VALUES (57, 'Spring Semester 2001');
INSERT INTO galleries (id, title) VALUES (58, 'Spring Weekend 2001');
INSERT INTO galleries (id, title) VALUES (59, 'Reading Period and Finals 2001');
INSERT INTO galleries (id, title) VALUES (60, 'Senior Week 2001');
INSERT INTO galleries (id, title) VALUES (61, 'Campus Dance 2001');
INSERT INTO galleries (id, title) VALUES (62, 'Commencement Weekend 2001');
INSERT INTO galleries (id, title) VALUES (63, 'Commencement 2001');
INSERT INTO galleries (id, title) VALUES (64, 'Beca''s Early Fall');
INSERT INTO galleries (id, title) VALUES (65, 'Early Fall 2001');
INSERT INTO galleries (id, title) VALUES (66, 'Mid Fall 2001');
INSERT INTO galleries (id, title) VALUES (67, 'Java Spook 2001');
INSERT INTO galleries (id, title) VALUES (68, 'More of the Spook 2001');
INSERT INTO galleries (id, title) VALUES (69, 'Late Fall');
INSERT INTO galleries (id, title) VALUES (70, 'Recruiting Season 2002');
INSERT INTO galleries (id, title) VALUES (71, 'Spring Break 2002');
INSERT INTO galleries (id, title) VALUES (72, 'Spring 2002');
INSERT INTO galleries (id, title) VALUES (73, 'The End of Year Dinner 2002');
INSERT INTO galleries (id, title) VALUES (74, 'Senior Week 2002');
INSERT INTO galleries (id, title) VALUES (75, 'Campus Dance 2002');
INSERT INTO galleries (id, title) VALUES (76, 'Commencement Weekend 2002');
INSERT INTO galleries (id, title) VALUES (77, 'Commencement 2002');
INSERT INTO galleries (id, title) VALUES (78, 'Summer 2002');
INSERT INTO galleries (id, title) VALUES (79, 'Orientation Week 2002');
INSERT INTO galleries (id, title) VALUES (80, 'Early Fall 2002');
INSERT INTO galleries (id, title) VALUES (81, 'Bench Removal');
INSERT INTO galleries (id, title) VALUES (82, 'Midfall 2002');
INSERT INTO galleries (id, title) VALUES (83, 'Javaspook');
INSERT INTO galleries (id, title) VALUES (84, 'Late Fall');
INSERT INTO galleries (id, title) VALUES (85, 'Recruiting Season 2003');
INSERT INTO galleries (id, title) VALUES (86, 'Spring ''03 Techtime');
INSERT INTO galleries (id, title) VALUES (87, 'Mid Spring ''03');
INSERT INTO galleries (id, title) VALUES (88, 'Spring Break Dinner ''03');
INSERT INTO galleries (id, title) VALUES (89, 'Techno House');
INSERT INTO galleries (id, title) VALUES (90, 'Bellydance Night');
INSERT INTO galleries (id, title) VALUES (91, 'Spring Weekend 03');
INSERT INTO galleries (id, title) VALUES (92, 'Project Glory');
INSERT INTO galleries (id, title) VALUES (93, 'T-Shirt Designs 2002-2003');
INSERT INTO galleries (id, title) VALUES (94, 'Hair Dye Night');
INSERT INTO galleries (id, title) VALUES (95, 'Semiformal 03');
INSERT INTO galleries (id, title) VALUES (96, 'Mutants & Mammaries');
INSERT INTO galleries (id, title) VALUES (97, 'Armory Upgrade: Project Death Ray');
INSERT INTO galleries (id, title) VALUES (98, 'EOY Dinner 03');
INSERT INTO galleries (id, title) VALUES (99, 'Some Games');
INSERT INTO galleries (id, title) VALUES (100, 'Some Weapons Practice');
INSERT INTO galleries (id, title) VALUES (101, 'More Glory!');
INSERT INTO galleries (id, title) VALUES (102, 'Senior Week 2003');
INSERT INTO galleries (id, title) VALUES (103, 'Commencement 2003');
INSERT INTO galleries (id, title) VALUES (104, 'Summer 2003');
INSERT INTO galleries (id, title) VALUES (105, 'Activities Night 2003');
INSERT INTO galleries (id, title) VALUES (106, 'Setup 2003');
INSERT INTO galleries (id, title) VALUES (107, 'Ambush Photos (misc.) - Fall 2003');
INSERT INTO galleries (id, title) VALUES (108, 'Bola Tag 2003');
INSERT INTO galleries (id, title) VALUES (109, 'Early Fall Barbecue');
INSERT INTO galleries (id, title) VALUES (110, 'Techhouse 2003-2004 Group Photos');
INSERT INTO galleries (id, title) VALUES (111, 'TechGrrrls Night Out');
INSERT INTO galleries (id, title) VALUES (112, 'Spoofers');
INSERT INTO galleries (id, title) VALUES (113, 'Ninjas');
INSERT INTO galleries (id, title) VALUES (114, 'Javaspook 2003');
INSERT INTO galleries (id, title) VALUES (115, 'Javaspook IX: The Alumni Invasion');
INSERT INTO galleries (id, title) VALUES (116, 'Thanksgiving 2003');
INSERT INTO galleries (id, title) VALUES (117, 'EOS Dinner 2003');
INSERT INTO galleries (id, title) VALUES (118, 'Super Bowl XXXVIII');
INSERT INTO galleries (id, title) VALUES (119, 'Hanging Out');
INSERT INTO galleries (id, title) VALUES (120, 'Ambush Photos (misc.) - Spring 2004');
INSERT INTO galleries (id, title) VALUES (121, 'Recruiting Season 2004');
INSERT INTO galleries (id, title) VALUES (122, 'Movie of the Week');
INSERT INTO galleries (id, title) VALUES (123, 'Drop Night 2004');
INSERT INTO galleries (id, title) VALUES (124, 'Blurry Indoor Paintball');
INSERT INTO galleries (id, title) VALUES (125, 'Around The World');
INSERT INTO galleries (id, title) VALUES (126, 'Serge Comes To Visit');
INSERT INTO galleries (id, title) VALUES (127, 'Jane''s Goodbye Party');
INSERT INTO galleries (id, title) VALUES (128, 'Eric''s Hair & Static');
INSERT INTO galleries (id, title) VALUES (129, 'Semiformal 2004 - Lou''s Louau');
INSERT INTO galleries (id, title) VALUES (130, 'Regime Change');
INSERT INTO galleries (id, title) VALUES (131, '2004XXWorkbenchLegs');
INSERT INTO galleries (id, title) VALUES (132, 'Spring BBQ 2004');
INSERT INTO galleries (id, title) VALUES (133, 'New Officers');
INSERT INTO galleries (id, title) VALUES (134, 'Late May');
INSERT INTO galleries (id, title) VALUES (135, 'Crazy Lou''s Crazy Barbecue');
INSERT INTO galleries (id, title) VALUES (136, 'Campus Dance 2004');
INSERT INTO galleries (id, title) VALUES (137, 'TH Alumni BBQ 2004');
INSERT INTO galleries (id, title) VALUES (138, 'WaterFire, May 29, 2004');
INSERT INTO galleries (id, title) VALUES (139, 'Other Commencement 2004 Photos');
INSERT INTO galleries (id, title) VALUES (140, 'Commencement Day 2004');
INSERT INTO galleries (id, title) VALUES (141, 'The After Party');
INSERT INTO galleries (id, title) VALUES (142, 'A Collection of Finals and Graduation Week Photos');
INSERT INTO galleries (id, title) VALUES (143, '2004 Group Photo');
INSERT INTO galleries (id, title) VALUES (144, 'Ethernet Cable Making');
INSERT INTO galleries (id, title) VALUES (145, 'Ambush Photos 2004-2005');
INSERT INTO galleries (id, title) VALUES (146, 'Setting Up The Macquarium, Round II');
INSERT INTO galleries (id, title) VALUES (147, 'TechTime 10/15/2004');
INSERT INTO galleries (id, title) VALUES (148, 'Couch Scouting (Colors Are Not Actual Due to Lighting and Browsers)');
INSERT INTO galleries (id, title) VALUES (149, 'Fall Firecream');
INSERT INTO galleries (id, title) VALUES (150, 'Rug Scouting');
INSERT INTO galleries (id, title) VALUES (151, 'Firecream 2005.02.03');
INSERT INTO galleries (id, title) VALUES (152, 'Stuff Night');
INSERT INTO galleries (id, title) VALUES (153, 'Hallway Party 2005.02.07');
INSERT INTO galleries (id, title) VALUES (154, 'Stuff Night II: Judgment Stuff');
INSERT INTO galleries (id, title) VALUES (155, 'SPAM Poetry Night');
INSERT INTO galleries (id, title) VALUES (156, 'Blow $417 Up Night + Things You Shouldn''t Microwave');
INSERT INTO galleries (id, title) VALUES (157, 'Drop Night 2005');
INSERT INTO galleries (id, title) VALUES (158, 'Stuff vs. Things');
INSERT INTO galleries (id, title) VALUES (159, 'An MTSR For The MTSS, And Miscellaneous');
INSERT INTO galleries (id, title) VALUES (160, 'While Playing Some DDR');
INSERT INTO galleries (id, title) VALUES (161, 'Lens Testing');
INSERT INTO galleries (id, title) VALUES (162, 'A Brief Packing Peanuts Incident');
INSERT INTO galleries (id, title) VALUES (163, 'After The Ratty Dinner');
INSERT INTO galleries (id, title) VALUES (164, 'The Budget Review/Housing Lottery/Presidential Nominations Meeting');
INSERT INTO galleries (id, title) VALUES (165, 'Tech House Semiformal');
INSERT INTO galleries (id, title) VALUES (166, '2005 End Of Year Dinner');
INSERT INTO galleries (id, title) VALUES (167, 'A Second Floor Hall Party');
INSERT INTO galleries (id, title) VALUES (168, 'Commencement 2005');
INSERT INTO galleries (id, title) VALUES (169, 'A Second Floor Hall Party');
INSERT INTO galleries (id, title) VALUES (170, 'Weekly Meeting');
INSERT INTO galleries (id, title) VALUES (171, 'Stuff Night 10-28');
INSERT INTO galleries (id, title) VALUES (172, 'JavaSpook Setup');
INSERT INTO galleries (id, title) VALUES (173, 'JavaSpook 2005');
INSERT INTO galleries (id, title) VALUES (174, 'The Knife');
INSERT INTO galleries (id, title) VALUES (175, 'Lego Night 2006');
INSERT INTO galleries (id, title) VALUES (176, 'Beer appreciation night');
INSERT INTO galleries (id, title) VALUES (177, 'Painting the TH Logo');
INSERT INTO galleries (id, title) VALUES (178, 'Zombie Apocalypse');
INSERT INTO galleries (id, title) VALUES (179, 'Ceiling Cat');
INSERT INTO galleries (id, title) VALUES (180, 'Colin''s Rampage');
INSERT INTO galleries (id, title) VALUES (181, 'Hall Party!');
INSERT INTO galleries (id, title) VALUES (182, 'MAME Construction');
INSERT INTO galleries (id, title) VALUES (183, 'Sketchy 009');
INSERT INTO galleries (id, title) VALUES (184, 'Tech House Bar Construction');
INSERT INTO galleries (id, title) VALUES (185, 'TH Thanksgiving 06');
INSERT INTO galleries (id, title) VALUES (186, 'Spring 2007 BBQ');
INSERT INTO galleries (id, title) VALUES (187, 'Javaspook 2006');

-- 187 galleries, with a sum of 3794 photos.
